name = "Semantic Enjin"
license = "Apache 2.0"
licenselink = "https://go-enjin.github.io/LICENSE"
description = "The Semantic Go-Enjin theme."
homepage = "https://go-enjin.github.io/"

[author]
    name = "The Go-Enjin Team"
    homepage = "https://go-enjin.github.io"


#:
#: Base Styles
#:

## --*
#[semantic.style]
#    #color.working = "#1e90ff"
#    color.working = "#ff901e"
#    color.recover = "#708090"
#    color.resting = "#d3d3d3"
#    color.meditate = "#ffffff"
#    color.social = "#ffd700"
#    color.active = "#ffa500"
#    color.material = "#0277bd"
#    color.light = "#ffffff"
#    color.dark = "#1d1d1d"
#    overlay.light.bg = "rgba(0,0,0,0.34)"
#    overlay.light.fg = "var(--color--light)"
#    overlay.dark.bg = "rgba(0,0,0,0.77)"
#    overlay.dark.fg = "var(--color--light)"
#    primary.fg = "var(--color--dark)"
#    primary.bg = "var(--color--light)"
#    secondary.fg = "var(--color--light)"
#    secondary.bg = "var(--color--working)"
#    accent.fg = "var(--color--light)"
#    accent.bg = "var(--color--recover)"
#    highlight.fg = "var(--color--dark)"
#    highlight.bg = "var(--color--social)"
#    alternate.fg = "var(--color--dark)"
#    alternate.bg = "var(--color--resting)"
#
#    # default block theme settings
#    style.fg = "var(--primary--fg)"
#    style.bg = "var(--primary--bg)"
#    style.accent.fg = "var(--accent--fg)"
#    style.accent.bg = "var(--accent--bg)"
#    style.highlight.fg = "var(--highlight--fg)"
#    style.highlight.bg = "var(--highlight--bg)"
#    style.alternate.fg = "var(--alternate--fg)"
#    style.alternate.bg = "var(--alternate--bg)"
#    style.overlay.light.bg = "rgba(0,0,0,0.34)"
#    style.overlay.light.fg = "var(--color--light)"
#    style.overlay.dark.bg = "rgba(0,0,0,0.77)"
#    style.overlay.dark.fg = "var(--color--light)"
#
#    desktop.lg.column = "1440px"
#    desktop.lg.min-width = "1600px"
#    desktop.lg.padding = "134px"
#    desktop.md.column = "1200px"
#    desktop.md.min-width = "1440px"
#    desktop.md.padding = "124px"
#    desktop.sm.column = "1024px"
#    desktop.sm.min-width = "1200px"
#    desktop.sm.padding = "100px"
#    mobile.lg.column = "924px"
#    mobile.lg.min-width = "1024px"
#    mobile.lg.padding = "50px"
#    mobile.md.column = "768px"
#    mobile.md.min-width = "768px"
#    mobile.md.padding = "25px"
#    mobile.sm.column = "100%"
#    mobile.sm.min-width = "0px"
#    mobile.sm.padding = "10px"
#
#    page.flex.gap = "25px"
#    page.flex.gap--sm = "10px"
#    page.column = "var(.desktop--lg--column)"
#    page.column--padding = "var(--desktop--lg--padding)"
#    page.scroll-padding-top = "170px"
#
#    page.masthead.full-height = "64px"
#    page.masthead.real-height = "63px"
#    page.side-menu.width = "85vw"
#
#    page.heading.font-family = "'Source Sans Pro', sans-serif"
#    page.content.font-family = "'Source Serif Pro', serif"
#    page.monospace.font-family = "monospace"
#
#    page.h1.font-size = "28px"
#    page.h1.line-height = "28px"
#    page.h2.font-size = "20px"
#    page.h2.line-height = "20px"
#    page.h3.font-size = "16px"
#    page.h3.line-height = "16px"
#    page.h4.font-size = "16px"
#    page.h4.line-height = "16px"
#    page.h5.font-size = "14px"
#    page.h5.line-height = "14px"
#    page.h6.font-size = "14px"
#    page.h6.line-height = "14px"
#    page.heading.font-size = "var(--page--h2--font-size)"
#    page.content.font-size = "12px"
#
#    page.dropcap.font-family = "'Source Sans Pro', sans-serif"
#    page.dropcap.font-size = "inherit"
#
#    page.ani.duration.long = "0.8s"
#    page.ani.duration.short = "calc(var(--page--ani--duration--long) / 2)"
#    page.ani.duration.brief = "calc(var(--page--ani--duration--short) / 2)"
#    page.ani.duration.pause = "calc(var(--page--ani--duration--long) + var(--page--ani--duration--short))"
#
#    z.page = "0"
#    z.page--underlay = "250"
#    z.page--overlay = "500"
#    z.page--nav = "900"
#    z.menus = "1000"
#    z.menus--sub-menus = "1250"
#    z.menus--overlay = "1500"
#
#    fa.font-family = "Font Awesome 6 Free"
#    fa-solid.font-family = "var(--fa--font-family)"
#    fa-solid.font-weight = "900"
#    fa-regular.font-family = "var(--fa--font-family)"
#    fa-regular.font-weight = "400"
#    fa-brands.font-family = "var(--fa--font-family)"
#    fa-brands.font-weight = "400"

#    # neede for ::after icons
#    fa.solid.chevron-down = '"\f078"'
#    fa.solid.chevron-right = '"\f054"'
#    fa.solid.chevron-up = '"\f077"'
#    fa.solid.exclamation-circle = '"\f06a"'
#    fa.solid.info-circle = '"\f05a"'
#    fa.solid.link = '"\f0c1"'
#    fa.solid.question-circle = '"\f059"'
#    fa.solid.times = '"\f00d"'

## --icon--*--content
#[semantic.style.icon]
#    info.content = "var(--fa--solid--info-circle)"
#    warn.content = "var(--fa--solid--question-circle)"
#    error.content = "var(--fa--solid--exclamation-circle)"
#    opened.content = "var(--fa--solid--chevron-down)"
#    closed.content = "var(--fa--solid--chevron-right)"
#    delete.content = "var(--fa--solid--times)"
#    link.content = "var(--fa--solid--link)"
#    jumptop.content = "var(--fa--solid--chevron-up)"

#:
#: Theme Styles (:root)
#:

## --theme--primary--*
#[semantic.style.theme.primary]
#    fg = "var(--primary--fg)"
#    bg = "var(--primary--bg)"
#    border = "5px solid var(--theme--primary--overlay--light--bg)"
#    accent.fg = "var(--accent--fg)"
#    accent.bg = "var(--accent--bg)"
#    highlight.fg = "var(--highlight--fg)"
#    highlight.bg = "var(--highlight--bg)"
#    alternate.fg = "var(--alternate--fg)"
#    alternate.bg = "var(--alternate--bg)"
#    overlay.dark.fg = "var(--overlay--dark--fg)"
#    overlay.dark.bg = "var(--overlay--dark--bg)"
#    overlay.light.fg = "var(--overlay--light--fg)"
#    overlay.light.bg = "var(--overlay--light--bg)"
#
## --theme--secondary--*
#[semantic.style.theme.secondary]
#    fg = "var(--secondary--fg)"
#    bg = "var(--secondary--bg)"
#    border = "5px solid var(--theme--secondary--overlay--light--bg)"
#    accent.fg = "var(--accent--fg)"
#    accent.bg = "var(--accent--bg)"
#    highlight.fg = "var(--highlight--fg)"
#    highlight.bg = "var(--highlight--bg)"
#    alternate.fg = "var(--alternate--fg)"
#    alternate.bg = "var(--alternate--bg)"
#    overlay.dark.fg = "var(--overlay--dark--fg)"
#    overlay.dark.bg = "var(--overlay--dark--bg)"
#    overlay.light.fg = "var(--overlay--light--fg)"
#    overlay.light.bg = "var(--overlay--light--bg)"
